[project]
name = "potdict"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.1"
dependencies = [
    "bs4>=0.0.2",
    "levenshtein>=0.27.1",
    "pillow>=11.2.1",
    "pyinstaller>=6.13.0",
    "pystray>=0.19.5",
    "python-lzo",
    "readmdict>=0.1.1",
    "requests>=2.32.3",
    "tkinterweb>=4.3.1",
]

[tool.uv.sources]
python-lzo = { git = "https://github.com/jd-boyd/python-lzo" }
